config/routes.rb
Chezhongguo::Application.routes.draw do




  resources :articles

  resources :autoparts

  resources :car_models

  get "answers/create"

  get "answers/destory"


  resources :questions do 
    resources :answers
     collection do
       get 'search'
       get 'tags'
       get 'experts'
       get 'unanswered'
       get 'my'
       get 'node'
     end
  end

  get "search/index"

  get "search/cars"

  if Rails.env.development? 
    get "/images/*path" => "gridfs#serve"
  end

  resources :cars do 
    resources :parameters
  end

  #authenticated :user do
  #  root :to => 'home#index'
  #end

  root :to => "home#index"

  devise_for :users
  resources :users, :only => [:show, :index]

  resources :brands, :only => [:show, :index]    

  resources :nodes

#  get "questions/node:id" => "questions#node", as: :nodequestions



  #----------------------------------- admin -----------------------------------
  namespace :admin do
    root :to => "home#index"

    resources :makers 
    resources :car_models 
    resources :cars
    resources :nodes
    resources :users

    resources :questions do 
      resources :answers
    end
 
    resources :brands do
      resources :makers 
    end
  end
  #................................... admin ...................................

end

app/models/autopart.rb
class Autopart
  include Mongoid::Document
  field :name, type: String
  field :price, type: String
  field :image, type: String
  field :description, type: String
  field :remote_url, type: String
end

app/controllers/autoparts_controller.rb
class AutopartsController < ApplicationController
  # GET /autoparts
  # GET /autoparts.json
  def index
    @autoparts = Autopart.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @autoparts }
    end
  end

  # GET /autoparts/1
  # GET /autoparts/1.json
  def show
    @autopart = Autopart.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @autopart }
    end
  end

  # GET /autoparts/new
  # GET /autoparts/new.json
  def new
    @autopart = Autopart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @autopart }
    end
  end

  # GET /autoparts/1/edit
  def edit
    @autopart = Autopart.find(params[:id])
  end

  # POST /autoparts
  # POST /autoparts.json
  def create
    @autopart = Autopart.new(autopart_params)

    respond_to do |format|
      if @autopart.save
        format.html { redirect_to @autopart, notice: 'Autopart was successfully created.' }
        format.json { render json: @autopart, status: :created, location: @autopart }
      else
        format.html { render action: "new" }
        format.json { render json: @autopart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /autoparts/1
  # PUT /autoparts/1.json
  def update
    @autopart = Autopart.find(params[:id])

    respond_to do |format|
      if @autopart.update_attributes(autopart_params)
        format.html { redirect_to @autopart, notice: 'Autopart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @autopart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /autoparts/1
  # DELETE /autoparts/1.json
  def destroy
    @autopart = Autopart.find(params[:id])
    @autopart.destroy

    respond_to do |format|
      format.html { redirect_to autoparts_url }
      format.json { head :no_content }
    end
  end

  def autopart_params
    params.require(:autopart).permit(:name, :price, :image, :description, :remote_url)
  end
end

app/helpers/autoparts_helper.rb
module AutopartsHelper
end

app/views/autoparts/_form.html.erb
<%= form_for(@autopart) do |f| %>
  <% if @autopart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@autopart.errors.count, "error") %> prohibited this autopart from being saved:</h2>

      <ul>
      <% @autopart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :remote_url %><br />
    <%= f.text_field :remote_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/autoparts/edit.html.erb
<h1>Editing autopart</h1>

<%= render 'form' %>

<%= link_to 'Show', @autopart %> |
<%= link_to 'Back', autoparts_path %>

app/views/autoparts/index.html.erb
<h1>车灯型号查询</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Price</th>
    <th>Image</th>
    <th>Description</th>
  </tr>

<% @autoparts.each do |autopart| %>
  <tr>
    <td><%= autopart.name %></td>
    <td><%= autopart.price %></td>
    <td><%= autopart.image %></td>
    <td><%= autopart.description %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Autopart', new_autopart_path %>

app/views/autoparts/new.html.erb
<h1>New autopart</h1>

<%= render 'form' %>

<%= link_to 'Back', autoparts_path %>

app/views/autoparts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @autopart.name %>
</p>

<p>
  <b>Price:</b>
  <%= @autopart.price %>
</p>

<p>
  <b>Image:</b>
  <%= @autopart.image %>
</p>

<p>
  <b>Description:</b>
  <%= @autopart.description %>
</p>

<p>
  <b>Remote url:</b>
  <%= @autopart.remote_url %>
</p>


<%= link_to 'Edit', edit_autopart_path(@autopart) %> |
<%= link_to 'Back', autoparts_path %>