config/routes.rb
Chezhongguo::Application.routes.draw do




  resources :articles

  resources :autoparts

  resources :car_models

  get "answers/create"

  get "answers/destory"


  resources :questions do 
    resources :answers
     collection do
       get 'search'
       get 'tags'
       get 'experts'
       get 'unanswered'
       get 'my'
       get 'node'
     end
  end

  get "search/index"

  get "search/cars"

  if Rails.env.development? 
    get "/images/*path" => "gridfs#serve"
  end

  resources :cars do 
    resources :parameters
  end

  #authenticated :user do
  #  root :to => 'home#index'
  #end

  root :to => "home#index"

  devise_for :users
  resources :users, :only => [:show, :index]

  resources :brands, :only => [:show, :index]    

  resources :nodes

#  get "questions/node:id" => "questions#node", as: :nodequestions



  #----------------------------------- admin -----------------------------------
  namespace :admin do
    root :to => "home#index"

    resources :makers 
    resources :car_models 
    resources :cars
    resources :nodes
    resources :users

    resources :questions do 
      resources :answers
    end
 
    resources :brands do
      resources :makers 
    end
  end
  #................................... admin ...................................

end

app/models/brand.rb
class Brand
  include Mongoid::Document
  include Mongoid::Timestamps

  #名称，logo，国家，品牌说明，logo说明
  field :name, type: String
  field :name_pinyin, type: String
  field :name_en, type: String
  field :country, type: String
  field :class_tag, type: String
 
  field :brand_summary, type: String
  field :logo_summary, type: String
  field :display_index, type: Integer
  field :hot_index, type: Integer

  field :temp_logo_url, type: String
  
  mount_uploader :logo_image, PhotoUploader

  index({name: 1})
  index({name_pinyin: 1})
  

  scope :search_name, lambda { |name| where(:name => /#{name}/) }
  scope :serial_brands, lambda { |serial| where( :class_tag => serial )}

  has_many :makers, :dependent => :destroy

  before_save :update_name_pinyin

protected
  def update_name_pinyin
    self.name_pinyin = Pinyin.t(self.name, '').downcase.to_s 
  end
end

app/controllers/admin/brands_controller.rb
# encoding: utf-8
class Admin::BrandsController < Admin::ApplicationController
  # GET /admin/brands
  # GET /admin/brands.json
  def index
    page = params[:page]
    @brands = Brand.page(page)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @brands }
    end
  end

  # GET /admin/brands/1
  # GET /admin/brands/1.json
  def show
    @brand = Brand.find(params[:id])
    @makers = @brand.makers

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @brand }
    end
  end

  # GET /admin/brands/new
  # GET /admin/brands/new.json
  def new
    @brand = Brand.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /admin/brands/1/edit
  def edit
    @brand = Brand.find(params[:id])
  end

  # POST /admin/brands
  # POST /admin/brands.json
  def create
    @brand = Brand.new(params[:brand])

    respond_to do |format|
      if @brand.save
        format.html { redirect_to [:admin, @brand], notice: 'Brand was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /admin/brands/1
  # PUT /admin/brands/1.json
  def update
    @brand = Brand.find(params[:id])

    respond_to do |format|
      if @brand.update_attributes(params[:brand])
        format.html { redirect_to [:admin, @brand], notice: 'Brand was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /admin/brands/1
  # DELETE /admin/brands/1.json
  def destroy
    @brand = Brand.find(params[:id])
    @brand.destroy

    respond_to do |format|
      format.html { redirect_to admin_brands_url }
    end
  end
end

app/controllers/brands_controller.rb
# encoding: utf-8
class BrandsController < ApplicationController

  def index
   @brands_hot = Brand.desc("hot_index").limit(20)
   @brands = Brand.all
    @brands_zz = []
    @brands_dx = []
    @brands_rh = []
    @brands_mx = []
    @brands_ox = []
    @brands_qt = []

    @brands.each do |brand|
      case brand.class_tag
      when "自主品牌" 
        @brands_zz << brand
      when "德系品牌"
        @brands_dx << brand
      when "日韩品牌"
        @brands_rh << brand
      when "美系品牌"
        @brands_mx << brand
      when "欧系品牌"
        @brands_ox << brand
      else
        @brands_qt << brand

      end
    end

    @page_title = "品牌大全"

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @brands }
    end
  end

  # GET /brands/1.json
  def show
    @brand = Brand.find(params[:id])
    #@makers = @brand.makers
    @page_title = @brand.name

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @brand }
    end
  end

end

app/helpers/admin/brands_helper.rb
module Admin::BrandsHelper
end

app/views/admin/brands/_form.html.erb
<%= form_for([:admin, @brand], :html => {:multipart => true } ) do |f| %>
  <% if @brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brand.errors.count, "error") %> prohibited this admin_brand from being saved:</h2>

      <ul>
        <% @brand.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">

    <%= f.label :logo_image, "local" %><br />

    <%= f.file_field :logo_image %>

    <%= f.label :remote_logo_image_url, "or remote" %>

    <%= f.text_field :remote_logo_image_url , :value =>  @brand.temp_logo_url %>

  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :name_en %><br />
    <%= f.text_field :name_en %>
  </div>
  <div class="field">
    <%= f.label :name_pinyin %><br />
    <%= f.text_field :name_pinyin %>
  </div>
  <div class="field">
    <%= f.label :display_index %><br />
    <%= f.text_field :display_index %>
  </div>
  <div class="field">
    <%= f.label :hot_index %><br />
    <%= f.text_field :hot_index %>
  </div>


  <div class="field">
    <%= f.label :class_tag %><br />
    <%= f.text_field :class_tag %>
  </div>

  <div class="field">
    <%= f.label :brand_summary %><br />
    <%= f.text_area :brand_summary, :rows => 3, :cols => 40 %>
  </div>
  <div class="field">
    <%= f.label :logo_summary %><br />
    <%= f.text_area :logo_summary, :rows => 3, :cols => 40 %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/brands/edit.html.erb
<h1>编辑品牌</h1>

<%= render 'form' %>

<% @nav_selected_item = 'brand' %>

<% content_for :site_nav do %>
  <%= link_to '后台', admin_root_path, :class => 'first' %>
  <span class="sep">&gt;</span>
  <%= link_to '品牌', admin_brands_path %>
  <span class="sep">&gt;</span>
  <label><%= @brand.name %></label>
<% end %>

app/views/admin/brands/index.html.erb
<div class="tools_bar">
  <span class="right">
    <%= link_to '新增', new_admin_brand_path, class: "btn btn-primary" %>
  </span>
  <%= paginate @brands %>
</div>
<table class="list">
  <tr>
    <th>ID</th>
    <th>品牌</th>
    <th>拼音</th>
    <th>国家</th>
    <th>操作</th>
  </tr>
  <% @brands.each do |admin_brand| %>
    <tr>
      <td style="width:10px; white-space:nowrap;"><%= admin_brand.id %></td>
      <td><%= link_to admin_brand.name, brand_path(admin_brand.id), :target => '_blank' %></td>
      <td><%= admin_brand.name_pinyin %></td>
      <td style="width:10px; white-space:nowrap;"><%= admin_brand.country %></td>
      <td class="operation">
        <%= link_to '详细', [:admin, admin_brand] %>
        <%= link_to '编辑', edit_admin_brand_path(admin_brand) %>
        <%= link_to '删除', [:admin, admin_brand], method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
  <% end %>
</table>

<% @nav_selected_item = 'brand' %>

<% content_for :search_bar do %>
  <form action="/admin/brands"  method="get">
    <input type="text" name="q" class="search-query span3" value="<%= params[:q] %>" placeholder="搜索" />
    <input type="submit" value="搜索" />
  </form>
<% end %>

<% content_for :site_nav do %>
  <%= link_to '后台', admin_root_path, :class => 'first' %>
  <span class="sep">&gt;</span>
  <%= link_to '品牌', admin_brands_path %>
  <span class="sep">&gt;</span>
  <span>列表</span>
<% end %>

app/views/admin/brands/new.html.erb
<h1>新增品牌</h1>

<%= render 'form' %>

<% @nav_selected_item = 'brand' %>

<% content_for :site_nav do %>
  <%= link_to '后台', admin_root_path, :class => 'first' %>
  <span class="sep">&gt;</span>
  <%= link_to '品牌', admin_brands_path %>
  <span class="sep">&gt;</span>
  <label>新增</label>
<% end %>

app/views/admin/brands/show.html.erb
<h1>品牌详细信息</h1>

<p id="notice"><%= notice %></p>

<p><%= image_tag @brand.logo_image_url.to_s %></p>

<p>
  <b>Name:</b>
  <%= @brand.name %>
</p>

<p>
  <b>Name pinyin:</b>
  <%= @brand.name_pinyin %>
</p>

<p>
  <b>Brand summary:</b>
  <%= @brand.brand_summary %>
</p>

<p>
  <b>Logo summary:</b>
  <%= @brand.logo_summary %>
</p>

<p>
  <b>Country:</b>
  <%= @brand.country %>
</p>

<h3>厂商</h3>

  <% unless  @makers.blank? %>
    <% @makers.each do |maker| %>
      <p><%= maker.name %></p>
      <p><%= maker.summary %></p>
      <p><%= maker.site %></p>
    <% end %>
  <% end %>

  <%= form_for(Maker.new ,:url => admin_brand_makers_path(@brand)) do |f| %>
    <p>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :summary %>
      <%= f.text_field :summary %>
    </p>
    <p>
      <%= f.label :site %>
      <%= f.text_field :site %>
    </p>

    <p><%= f.submit %></p>
  <% end %>

<% @nav_selected_item = 'brand' %>

<% content_for :site_nav do %>
  <%= link_to '后台', admin_root_path, :class => 'first' %>
  <span class="sep">&gt;</span>
  <%= link_to '品牌', admin_brands_path %>
  <span class="sep">&gt;</span>
  <label><%= @brand.name %></label>
<% end %>