config/routes.rb
Chezhongguo::Application.routes.draw do




  resources :articles

  resources :autoparts

  resources :car_models

  get "answers/create"

  get "answers/destory"


  resources :questions do 
    resources :answers
     collection do
       get 'search'
       get 'tags'
       get 'experts'
       get 'unanswered'
       get 'my'
       get 'node'
     end
  end

  get "search/index"

  get "search/cars"

  if Rails.env.development? 
    get "/images/*path" => "gridfs#serve"
  end

  resources :cars do 
    resources :parameters
  end

  #authenticated :user do
  #  root :to => 'home#index'
  #end

  root :to => "home#index"

  devise_for :users
  resources :users, :only => [:show, :index]

  resources :brands, :only => [:show, :index]    

  resources :nodes

#  get "questions/node:id" => "questions#node", as: :nodequestions



  #----------------------------------- admin -----------------------------------
  namespace :admin do
    root :to => "home#index"

    resources :makers 
    resources :car_models 
    resources :cars
    resources :nodes
    resources :users

    resources :questions do 
      resources :answers
    end
 
    resources :brands do
      resources :makers 
    end
  end
  #................................... admin ...................................

end

app/views/layouts/admin/_footer.html.erb
<div id="footer">
</div>

app/views/layouts/admin/_header.html.erb
<div id="header">
  <div class="nav">
    <ul class="<%= @nav_selected_item %>">
      <li class="home"><%= link_to '帮您配汽车网后台', admin_root_path %></li>
      <li class="car_model"><%= link_to '车型', admin_car_models_path %></li>
      <li class="car"><%= link_to '车款', admin_cars_path %></li>
      <li class="brand"><%= link_to '品牌', admin_brands_path %></li>
      <li class="news"><%= link_to '资讯', admin_brands_path %></li>
      <li class="aq"><%= link_to '问答', admin_questions_path %></li>
      <li class="node"><%= link_to '节点', admin_nodes_path %></li>
      <li class="user"><%= link_to '用户', admin_users_path %></li>
      <li class="more"><a href="javascript:">更多<b class="caret"></b></a></li>
    </ul>
    <span class="right">
      <% if user_signed_in? %>
        <label><%= link_to current_user.name, edit_user_registration_path %></label> 
        <%= link_to '退出', destroy_user_session_path, :method=>'delete' %>        
      <% else %>
        <%= link_to '登录', new_user_session_path %>  
        <%= link_to '注册', new_user_registration_path %>
      <% end %>
    </span>
  </div>
  <% if content_for?(:search_bar) %>
    <div id="search_bar">
      <%= yield :search_bar %>
    </div>
  <% end %>
  <% if content_for?(:site_nav) %>
    <div id="site_nav">
      <%= yield :site_nav %>
    </div>
  <% end %>
</div>
<div class="nav_more_menu">
  <ul>
    <li><%= link_to '参数设置', admin_root_path %></li>
    <li><%= link_to '权限管理', admin_root_path %></li>
    <li><%= link_to '修改密码', admin_root_path %></li>
  </ul>
</div>

app/views/layouts/admin/application.html.erb
<!doctype html>
<html>
  <head>
    <title>管理后台-帮您配汽车网</title>
    <%= stylesheet_link_tag    "admin", :media => "all" %>
    <%= javascript_include_tag "admin" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="container">
      <%= render 'layouts/admin/header' %>
      <div id="main">
        <% if content_for?(:left) %>
          <div id="main_wrapper">
            <div id="main_left">
              <%= yield :left %>
            </div>
            <div id="main_right">
              <%= yield :right %>
            </div>
          </div>
          <div class="clear_both"></div>
        <% elsif %>
          <%= yield %>
        <%end%>
      </div>
      <%= render 'layouts/admin/footer' %>
    </div>
  </body>
</html>