config/routes.rb
Chezhongguo::Application.routes.draw do




  resources :articles

  resources :autoparts

  resources :car_models

  get "answers/create"

  get "answers/destory"


  resources :questions do 
    resources :answers
     collection do
       get 'search'
       get 'tags'
       get 'experts'
       get 'unanswered'
       get 'my'
       get 'node'
     end
  end

  get "search/index"

  get "search/cars"

  if Rails.env.development? 
    get "/images/*path" => "gridfs#serve"
  end

  resources :cars do 
    resources :parameters
  end

  #authenticated :user do
  #  root :to => 'home#index'
  #end

  root :to => "home#index"

  devise_for :users
  resources :users, :only => [:show, :index]

  resources :brands, :only => [:show, :index]    

  resources :nodes

#  get "questions/node:id" => "questions#node", as: :nodequestions



  #----------------------------------- admin -----------------------------------
  namespace :admin do
    root :to => "home#index"

    resources :makers 
    resources :car_models 
    resources :cars
    resources :nodes
    resources :users

    resources :questions do 
      resources :answers
    end
 
    resources :brands do
      resources :makers 
    end
  end
  #................................... admin ...................................

end

app/models/car_model.rb
class CarModel
  include Mongoid::Document
  field :name, type: String
  field :name_pinyin, type: String
  field :name_en, type: String
  field :price_low, type: String   #厂商指导最低价
  field :price_top, type: String   #厂商指导最高价
  field :pailiang, type: Array, default: []     #排量 1.6L 2.0L 2.2L
  field :biansuxiang, type: Array, default: []  #变速箱 手动/自动
  field :status, type: String    #在产 停产 未上市
  field :country, type: String   #国家
  field :summary, type: String   #说明
  field :car_type, type: String   #微型车、中型车
  field :car_use, type: String    #家用、商用


  field :temp_model_url
  field :temp_pic_url

  mount_uploader :image, CarModelPhotoUploader


  belongs_to :maker
  has_many :cars
  scope :search_name, lambda { |name| where(:name => /#{name}/) }

end

app/controllers/admin/car_models_controller.rb
# encoding: utf-8
class Admin::CarModelsController < Admin::ApplicationController
  # GET /admin/car_models
  # GET /admin/car_models.json
  def index
    page = params[:page]
    @admin_car_models = CarModel.page(page)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admin_car_models }
    end
  end

  # GET /admin/car_models/1
  # GET /admin/car_models/1.json
  def show
    @admin_car_model = CarModel.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @admin_car_model }
    end
  end

  # GET /admin/car_models/new
  # GET /admin/car_models/new.json
  def new
    @admin_car_model = CarModel.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin_car_model }
    end
  end

  # GET /admin/car_models/1/edit
  def edit
    @admin_car_model = CarModel.find(params[:id])
  end

  # POST /admin/car_models
  # POST /admin/car_models.json
  def create
    @admin_car_model = CarModel.new(params[:admin_car_model])

    respond_to do |format|
      if @admin_car_model.save
        format.html { redirect_to @admin_car_model, notice: 'Car model was successfully created.' }
        format.json { render json: @admin_car_model, status: :created, location: @admin_car_model }
      else
        format.html { render action: "new" }
        format.json { render json: @admin_car_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/car_models/1
  # PUT /admin/car_models/1.json
  def update
    @admin_car_model = CarModel.find(params[:id])

    respond_to do |format|
      if @admin_car_model.update_attributes(params[:admin_car_model])
        format.html { redirect_to @admin_car_model, notice: 'Car model was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin_car_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/car_models/1
  # DELETE /admin/car_models/1.json
  def destroy
    @admin_car_model = CarModel.find(params[:id])
    @admin_car_model.destroy

    respond_to do |format|
      format.html { redirect_to admin_car_models_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/car_models_controller.rb
# encoding: utf-8
class CarModelsController < ApplicationController
  # GET /car_models
  # GET /car_models.json
  def index
    page = params[:page]
    @car_models = CarModel.page(page)
    @page_title = "全部车型"
    
    @brands = Brand.all.desc("hot_index")
    @brands_hot = @brands.hot_brands 

    @brands_zz = []
    @brands_dx = []
    @brands_rh = []
    @brands_mx = []
    @brands_ox = []
    @brands_qt = []

    @brands.each do |brand|
      case brand.class_tag
      when "自主品牌" 
        @brands_zz << brand
      when "德系品牌"
        @brands_dx << brand
      when "日韩品牌"
        @brands_rh << brand
      when "美系品牌"
        @brands_mx << brand
      when "欧系品牌"
        @brands_ox << brand
      else
        @brands_qt << brand

      end
    end


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @car_models }
    end
  end

  # GET /car_models/1
  # GET /car_models/1.json
  def show
    @car_model = CarModel.find(params[:id])
    @title = @car_model.name

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @car_model }
    end
  end
end

app/helpers/admin/car_models_helper.rb
module Admin::CarModelsHelper
end

app/helpers/car_model_helper.rb
module CarModelHelper
end

app/helpers/car_models_helper.rb
module CarModelsHelper
end

app/views/admin/car_models/_form.html.erb
<%= form_for([:admin, @admin_car_model], :html => {:multipart => true } ) do |f| %>
  <% if @admin_car_model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_car_model.errors.count, "error") %> prohibited this admin_car_model from being saved:</h2>

      <ul>
      <% @admin_car_model.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :name_pinyin %><br />
    <%= f.text_field :name_pinyin %>
  </div>
  <div class="field">
    <%= f.label :price_low %><br />
    <%= f.text_field :price_low %>
  </div>
  <div class="field">
    <%= f.label :price_top %><br />
    <%= f.text_field :price_top %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :summary %><br />
    <%= f.text_field :summary %>
  </div>
  <div class="field">
    <%= f.label :car_type %><br />
    <%= f.text_field :car_type %>
  </div>
  <div class="field">
    <%= f.label :car_use %><br />
    <%= f.text_field :car_use %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/car_models/edit.html.erb
<h1>Editing admin_car_model</h1>

<%= render 'form' %>

app/views/admin/car_models/index.html.erb
<div class="tools_bar">
  <span class="right">
    <%= link_to '新增', new_admin_car_model_path, class: "btn" %>
  </span>
  <%= paginate @admin_car_models %>
</div>
<table class="list">
  <tr>
    <th>Name</th>
    <th>Name pinyin</th>
    <th>Price low</th>
    <th>Price top</th>
    <th>Status</th>
    <th>Country</th>
    <th>Summary</th>
    <th>Type</th>
    <th>Use</th>
    <th></th>
  </tr>

<% @admin_car_models.each do |admin_car_model| %>
  <tr>
    <td><%= admin_car_model.name %></td>
    <td><%= admin_car_model.name_pinyin %></td>
    <td><%= admin_car_model.price_low %></td>
    <td><%= admin_car_model.price_top %></td>
    <td><%= admin_car_model.status %></td>
    <td><%= admin_car_model.country %></td>
    <td><%= admin_car_model.summary %></td>
    <td><%= admin_car_model.car_type %></td>
    <td><%= admin_car_model.car_use %></td>
      <td class="operation">
        <%= link_to '详细', [:admin, admin_car_model] %>
        <%= link_to '编辑', edit_admin_car_model_path(admin_car_model) %>
        <%= link_to '删除', [:admin, admin_car_model], method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
  </tr>
<% end %>
</table>

<% @nav_selected_item = 'car_model' %>

<% content_for :search_bar do %>
  <form action="/admin/car_models"  method="get">
    <input type="text" name="q" class="search-query span3" value="<%= params[:q] %>" placeholder="搜索" />
    <input type="submit" value="搜索" />
  </form>
<% end %>

<% content_for :site_nav do %>
  <%= link_to '后台', admin_root_path, :class => 'first' %>
  <span class="sep">&gt;</span>
  <%= link_to '车型', admin_car_models_path %>
  <span class="sep">&gt;</span>
  <label>列表</label>
<% end %>

app/views/admin/car_models/new.html.erb
<h1>New admin_car_model</h1>

<%= render 'form' %>

app/views/admin/car_models/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @admin_car_model.name %>
</p>

<p>
  <b>Name pinyin:</b>
  <%= @admin_car_model.name_pinyin %>
</p>

<p>
  <b>Price low:</b>
  <%= @admin_car_model.price_low %>
</p>

<p>
  <b>Price top:</b>
  <%= @admin_car_model.price_top %>
</p>

<p>
  <b>Status:</b>
  <%= @admin_car_model.status %>
</p>

<p>
  <b>Country:</b>
  <%= @admin_car_model.country %>
</p>

<p>
  <b>Summary:</b>
  <%= @admin_car_model.summary %>
</p>

<p>
  <b>Type:</b>
  <%= @admin_car_model.car_type %>
</p>

<p>
  <b>Use:</b>
  <%= @admin_car_model.car_use %>
</p>